---
type: wordpress
hooks:
  post-start:
    - exec: "wp core download"
    - exec: "wp core install --url='$DDEV_PRIMARY_URL' --title='WPScan Vulnerability Testbench' --admin_user=admin --admin_password=password --admin_email=admin@example.com"
