---
type: wordpress
hooks:
  post-start:
    - exec: "[ -f $DDEV_DOCROOT/index.php ] || wp core download"
    - exec: "wp core multisite-install --url='$DDEV_PRIMARY_URL' --title='WPScan Vulnerability Testbench' --admin_user=superadmin --admin_password=password --admin_email=admin@example.com"
    - exec: "wp user import-csv $DDEV_DOCROOT/.ddev/users.csv"
    - exec: "wp user update superadmin --display_name='Super Admin'"
