---
type: wordpress
hooks:
  post-start:
    - exec: "wp core download"
    - exec: "wp core multisite-install --url='$DDEV_PRIMARY_URL' --title='WPScan Vulnerability Testbench' --admin_user=superadmin --admin_password=password --admin_email=admin@example.com"
    - exec: "wp user create simpleadmin simpleadmin@example.com --user_pass=password --role=administrator"
    - exec: "wp user create subscriber subscriber@example.com --user_pass=password --role=subscriber"
    - exec: "wp user create author author@example.com --user_pass=password --role=author"
    - exec: "wp user create editor editor@example.com --user_pass=password --role=editor"
    - exec: "wp user create contributor contributor@example.com --user_pass=password --role=contributor"
